-- Add new notification types to the enum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TEAM_REGISTERED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TEAM_SELECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TEAM_WAITLISTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BADGE_UNLOCKED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TEAM_MESSAGE_RECEIVED';
