/** Liste complète des devises mondiales ISO 4217, compatible client et serveur */
export const CURRENCIES: { code: string; label: string }[] = [
  { code: "AED", label: "AED — Dirham (UAE)" },
  { code: "AFN", label: "AFN — Afghani" },
  { code: "ALL", label: "ALL — Lek (Albanie)" },
  { code: "AMD", label: "AMD — Dram (Arménie)" },
  { code: "ANG", label: "ANG — Florin (Antilles NL)" },
  { code: "AOA", label: "AOA — Kwanza (Angola)" },
  { code: "ARS", label: "ARS — Peso (Argentine)" },
  { code: "AUD", label: "AUD $ — Dollar (Australie)" },
  { code: "AWG", label: "AWG — Florin (Aruba)" },
  { code: "AZN", label: "AZN — Manat (Azerbaïdjan)" },
  { code: "BAM", label: "BAM — Mark (Bosnie-Herzégovine)" },
  { code: "BBD", label: "BBD — Dollar (Barbade)" },
  { code: "BDT", label: "BDT — Taka (Bangladesh)" },
  { code: "BGN", label: "BGN — Lev (Bulgarie)" },
  { code: "BHD", label: "BHD — Dinar (Bahreïn)" },
  { code: "BIF", label: "BIF — Franc (Burundi)" },
  { code: "BMD", label: "BMD — Dollar (Bermudes)" },
  { code: "BND", label: "BND — Dollar (Brunei)" },
  { code: "BOB", label: "BOB — Boliviano (Bolivie)" },
  { code: "BRL", label: "BRL R$ — Real (Brésil)" },
  { code: "BSD", label: "BSD — Dollar (Bahamas)" },
  { code: "BTN", label: "BTN — Ngultrum (Bhoutan)" },
  { code: "BWP", label: "BWP — Pula (Botswana)" },
  { code: "BYN", label: "BYN — Rouble (Biélorussie)" },
  { code: "BZD", label: "BZD — Dollar (Belize)" },
  { code: "CAD", label: "CAD $ — Dollar (Canada)" },
  { code: "CDF", label: "CDF — Franc (Congo RDC)" },
  { code: "CHF", label: "CHF — Franc (Suisse)" },
  { code: "CLP", label: "CLP — Peso (Chili)" },
  { code: "CNY", label: "CNY ¥ — Yuan (Chine)" },
  { code: "COP", label: "COP — Peso (Colombie)" },
  { code: "CRC", label: "CRC — Colón (Costa Rica)" },
  { code: "CUP", label: "CUP — Peso (Cuba)" },
  { code: "CVE", label: "CVE — Escudo (Cap-Vert)" },
  { code: "CZK", label: "CZK — Couronne (Tchéquie)" },
  { code: "DJF", label: "DJF — Franc (Djibouti)" },
  { code: "DKK", label: "DKK — Couronne (Danemark)" },
  { code: "DOP", label: "DOP — Peso (Rép. Dominicaine)" },
  { code: "DZD", label: "DZD — Dinar (Algérie)" },
  { code: "EGP", label: "EGP — Livre (Égypte)" },
  { code: "ERN", label: "ERN — Nakfa (Érythrée)" },
  { code: "ETB", label: "ETB — Birr (Éthiopie)" },
  { code: "EUR", label: "EUR € — Euro" },
  { code: "FJD", label: "FJD — Dollar (Fidji)" },
  { code: "FKP", label: "FKP — Livre (Falkland)" },
  { code: "GBP", label: "GBP £ — Livre (Royaume-Uni)" },
  { code: "GEL", label: "GEL — Lari (Géorgie)" },
  { code: "GHS", label: "GHS — Cedi (Ghana)" },
  { code: "GIP", label: "GIP — Livre (Gibraltar)" },
  { code: "GMD", label: "GMD — Dalasi (Gambie)" },
  { code: "GNF", label: "GNF — Franc (Guinée)" },
  { code: "GTQ", label: "GTQ — Quetzal (Guatemala)" },
  { code: "GYD", label: "GYD — Dollar (Guyana)" },
  { code: "HKD", label: "HKD — Dollar (Hong Kong)" },
  { code: "HNL", label: "HNL — Lempira (Honduras)" },
  { code: "HTG", label: "HTG — Gourde (Haïti)" },
  { code: "HUF", label: "HUF — Forint (Hongrie)" },
  { code: "IDR", label: "IDR — Roupie (Indonésie)" },
  { code: "ILS", label: "ILS — Shekel (Israël)" },
  { code: "INR", label: "INR ₹ — Roupie (Inde)" },
  { code: "IQD", label: "IQD — Dinar (Irak)" },
  { code: "IRR", label: "IRR — Rial (Iran)" },
  { code: "ISK", label: "ISK — Couronne (Islande)" },
  { code: "JMD", label: "JMD — Dollar (Jamaïque)" },
  { code: "JOD", label: "JOD — Dinar (Jordanie)" },
  { code: "JPY", label: "JPY ¥ — Yen (Japon)" },
  { code: "KES", label: "KES — Shilling (Kenya)" },
  { code: "KGS", label: "KGS — Som (Kirghizistan)" },
  { code: "KHR", label: "KHR — Riel (Cambodge)" },
  { code: "KMF", label: "KMF — Franc (Comores)" },
  { code: "KRW", label: "KRW ₩ — Won (Corée du Sud)" },
  { code: "KWD", label: "KWD — Dinar (Koweït)" },
  { code: "KYD", label: "KYD — Dollar (Îles Caïmans)" },
  { code: "KZT", label: "KZT — Tenge (Kazakhstan)" },
  { code: "LAK", label: "LAK — Kip (Laos)" },
  { code: "LBP", label: "LBP — Livre (Liban)" },
  { code: "LKR", label: "LKR — Roupie (Sri Lanka)" },
  { code: "LRD", label: "LRD — Dollar (Liberia)" },
  { code: "LSL", label: "LSL — Loti (Lesotho)" },
  { code: "LYD", label: "LYD — Dinar (Libye)" },
  { code: "MAD", label: "MAD — Dirham (Maroc)" },
  { code: "MDL", label: "MDL — Leu (Moldavie)" },
  { code: "MGA", label: "MGA — Ariary (Madagascar)" },
  { code: "MKD", label: "MKD — Denar (Macédoine)" },
  { code: "MMK", label: "MMK — Kyat (Myanmar)" },
  { code: "MNT", label: "MNT — Tögrög (Mongolie)" },
  { code: "MOP", label: "MOP — Pataca (Macao)" },
  { code: "MRU", label: "MRU — Ouguiya (Mauritanie)" },
  { code: "MUR", label: "MUR — Roupie (Maurice)" },
  { code: "MVR", label: "MVR — Rufiyaa (Maldives)" },
  { code: "MWK", label: "MWK — Kwacha (Malawi)" },
  { code: "MXN", label: "MXN — Peso (Mexique)" },
  { code: "MYR", label: "MYR — Ringgit (Malaisie)" },
  { code: "MZN", label: "MZN — Metical (Mozambique)" },
  { code: "NAD", label: "NAD — Dollar (Namibie)" },
  { code: "NGN", label: "NGN — Naira (Nigeria)" },
  { code: "NIO", label: "NIO — Córdoba (Nicaragua)" },
  { code: "NOK", label: "NOK — Couronne (Norvège)" },
  { code: "NPR", label: "NPR — Roupie (Népal)" },
  { code: "NZD", label: "NZD — Dollar (Nouvelle-Zélande)" },
  { code: "OMR", label: "OMR — Rial (Oman)" },
  { code: "PAB", label: "PAB — Balboa (Panama)" },
  { code: "PEN", label: "PEN — Sol (Pérou)" },
  { code: "PGK", label: "PGK — Kina (PNG)" },
  { code: "PHP", label: "PHP — Peso (Philippines)" },
  { code: "PKR", label: "PKR — Roupie (Pakistan)" },
  { code: "PLN", label: "PLN — Złoty (Pologne)" },
  { code: "PYG", label: "PYG — Guaraní (Paraguay)" },
  { code: "QAR", label: "QAR — Riyal (Qatar)" },
  { code: "RON", label: "RON — Leu (Roumanie)" },
  { code: "RSD", label: "RSD — Dinar (Serbie)" },
  { code: "RUB", label: "RUB — Rouble (Russie)" },
  { code: "RWF", label: "RWF — Franc (Rwanda)" },
  { code: "SAR", label: "SAR — Riyal (Arabie Saoudite)" },
  { code: "SBD", label: "SBD — Dollar (Salomon)" },
  { code: "SCR", label: "SCR — Roupie (Seychelles)" },
  { code: "SDG", label: "SDG — Livre (Soudan)" },
  { code: "SEK", label: "SEK — Couronne (Suède)" },
  { code: "SGD", label: "SGD — Dollar (Singapour)" },
  { code: "SHP", label: "SHP — Livre (Sainte-Hélène)" },
  { code: "SLE", label: "SLE — Leone (Sierra Leone)" },
  { code: "SOS", label: "SOS — Shilling (Somalie)" },
  { code: "SRD", label: "SRD — Dollar (Suriname)" },
  { code: "STN", label: "STN — Dobra (São Tomé)" },
  { code: "SVC", label: "SVC — Colón (El Salvador)" },
  { code: "SYP", label: "SYP — Livre (Syrie)" },
  { code: "SZL", label: "SZL — Lilangeni (Eswatini)" },
  { code: "THB", label: "THB — Baht (Thaïlande)" },
  { code: "TJS", label: "TJS — Somoni (Tadjikistan)" },
  { code: "TMT", label: "TMT — Manat (Turkménistan)" },
  { code: "TND", label: "TND — Dinar (Tunisie)" },
  { code: "TOP", label: "TOP — Paʻanga (Tonga)" },
  { code: "TRY", label: "TRY — Lire (Turquie)" },
  { code: "TTD", label: "TTD — Dollar (Trinidad)" },
  { code: "TWD", label: "TWD — Dollar (Taïwan)" },
  { code: "TZS", label: "TZS — Shilling (Tanzanie)" },
  { code: "UAH", label: "UAH — Hryvnia (Ukraine)" },
  { code: "UGX", label: "UGX — Shilling (Ouganda)" },
  { code: "USD", label: "USD $ — Dollar (États-Unis)" },
  { code: "UYU", label: "UYU — Peso (Uruguay)" },
  { code: "UZS", label: "UZS — Som (Ouzbékistan)" },
  { code: "VES", label: "VES — Bolívar (Venezuela)" },
  { code: "VND", label: "VND — Đồng (Viêt Nam)" },
  { code: "VUV", label: "VUV — Vatu (Vanuatu)" },
  { code: "WST", label: "WST — Tālā (Samoa)" },
  { code: "XAF", label: "XAF — Franc CFA (Afrique C.)" },
  { code: "XCD", label: "XCD — Dollar (Caraïbes E.)" },
  { code: "XOF", label: "XOF — Franc CFA (Afrique O.)" },
  { code: "XPF", label: "XPF — Franc CFP (Pacifique)" },
  { code: "YER", label: "YER — Rial (Yémen)" },
  { code: "ZAR", label: "ZAR — Rand (Afrique du Sud)" },
  { code: "ZMW", label: "ZMW — Kwacha (Zambie)" },
  { code: "ZWL", label: "ZWL — Dollar (Zimbabwe)" },
];

/** Mapping pays (nom anglais) → code devise ISO 4217 */
export const COUNTRY_TO_CURRENCY: Record<string, string> = {
  Afghanistan: "AFN", Albania: "ALL", Algeria: "DZD", Andorra: "EUR",
  Angola: "AOA", "Antigua and Barbuda": "XCD", Argentina: "ARS", Armenia: "AMD",
  Australia: "AUD", Austria: "EUR", Azerbaijan: "AZN", Bahamas: "BSD",
  Bahrain: "BHD", Bangladesh: "BDT", Barbados: "BBD", Belarus: "BYN",
  Belgium: "EUR", Belize: "BZD", Benin: "XOF", Bhutan: "BTN",
  Bolivia: "BOB", "Bosnia and Herzegovina": "BAM", Botswana: "BWP", Brazil: "BRL",
  Brunei: "BND", Bulgaria: "BGN", "Burkina Faso": "XOF", Burundi: "BIF",
  "Cabo Verde": "CVE", Cambodia: "KHR", Cameroon: "XAF", Canada: "CAD",
  "Central African Republic": "XAF", Chad: "XAF", Chile: "CLP", China: "CNY",
  Colombia: "COP", Comoros: "KMF", Congo: "XAF", "Congo (DRC)": "CDF",
  "Costa Rica": "CRC", "Côte d'Ivoire": "XOF", Croatia: "EUR", Cuba: "CUP",
  Cyprus: "EUR", "Czech Republic": "CZK", Denmark: "DKK", Djibouti: "DJF",
  Dominica: "XCD", "Dominican Republic": "DOP", Ecuador: "USD", Egypt: "EGP",
  "El Salvador": "USD", Eritrea: "ERN", Estonia: "EUR", Eswatini: "SZL",
  Ethiopia: "ETB", Fiji: "FJD", Finland: "EUR", France: "EUR",
  Gabon: "XAF", Gambia: "GMD", Georgia: "GEL", Germany: "EUR",
  Ghana: "GHS", Greece: "EUR", Guatemala: "GTQ", Guinea: "GNF",
  "Guinea-Bissau": "XOF", Guyana: "GYD", Haiti: "HTG", Honduras: "HNL",
  "Hong Kong": "HKD", Hungary: "HUF", Iceland: "ISK", India: "INR",
  Indonesia: "IDR", Iran: "IRR", Iraq: "IQD", Ireland: "EUR",
  Israel: "ILS", Italy: "EUR", Jamaica: "JMD", Japan: "JPY",
  Jordan: "JOD", Kazakhstan: "KZT", Kenya: "KES", Kiribati: "AUD",
  Kosovo: "EUR", Kuwait: "KWD", Kyrgyzstan: "KGS", Laos: "LAK",
  Latvia: "EUR", Lebanon: "LBP", Lesotho: "LSL", Liberia: "LRD",
  Libya: "LYD", Liechtenstein: "CHF", Lithuania: "EUR", Luxembourg: "EUR",
  Madagascar: "MGA", Malawi: "MWK", Malaysia: "MYR", Maldives: "MVR",
  Mali: "XOF", Malta: "EUR", Mauritania: "MRU", Mauritius: "MUR",
  Mexico: "MXN", Moldova: "MDL", Monaco: "EUR", Mongolia: "MNT",
  Montenegro: "EUR", Morocco: "MAD", Mozambique: "MZN", Myanmar: "MMK",
  Namibia: "NAD", Nepal: "NPR", Netherlands: "EUR", "New Zealand": "NZD",
  Nicaragua: "NIO", Niger: "XOF", Nigeria: "NGN", "North Macedonia": "MKD",
  Norway: "NOK", Oman: "OMR", Pakistan: "PKR", Palau: "USD",
  Panama: "PAB", "Papua New Guinea": "PGK", Paraguay: "PYG", Peru: "PEN",
  Philippines: "PHP", Poland: "PLN", Portugal: "EUR", "Puerto Rico": "USD",
  Qatar: "QAR", Romania: "RON", Russia: "RUB", Rwanda: "RWF",
  "Saint Kitts and Nevis": "XCD", "Saint Lucia": "XCD", "Saint Vincent and the Grenadines": "XCD",
  Samoa: "WST", "San Marino": "EUR", "Saudi Arabia": "SAR", Senegal: "XOF",
  Serbia: "RSD", Seychelles: "SCR", "Sierra Leone": "SLE", Singapore: "SGD",
  Slovakia: "EUR", Slovenia: "EUR", "Solomon Islands": "SBD", Somalia: "SOS",
  "South Africa": "ZAR", "South Korea": "KRW", "South Sudan": "SSP",
  Spain: "EUR", "Sri Lanka": "LKR", Sudan: "SDG", Suriname: "SRD",
  Sweden: "SEK", Switzerland: "CHF", Syria: "SYP", Taiwan: "TWD",
  Tajikistan: "TJS", Tanzania: "TZS", Thailand: "THB", "Timor-Leste": "USD",
  Togo: "XOF", Tonga: "TOP", "Trinidad and Tobago": "TTD", Tunisia: "TND",
  Turkey: "TRY", Turkmenistan: "TMT", Uganda: "UGX", Ukraine: "UAH",
  "United Arab Emirates": "AED", "United Kingdom": "GBP", "United States": "USD",
  Uruguay: "UYU", Uzbekistan: "UZS", Vanuatu: "VUV", Venezuela: "VES",
  Vietnam: "VND", Yemen: "YER", Zambia: "ZMW", Zimbabwe: "ZWL",
};
